### ISSUE TITLE
Haptics are delayed in Beatsaber

### ISSUE THREAD

**Issue by WattleFoxxo** [mm0zct/Oculus_Touch_Steam_Link#10]
In the menu it's responsive but once the level starts the haptics get more and more delayed.

Specs:
HMD: HP Reverb G2.
OS: Windows 11 Pro 64 bit.
CPU: Ryzen 7 7700X.
RAM: 32 GB DDR5
GPU: AMD RX 6800XT

**Comment by mm0zct** [comment]
Thanks for the issue report, I had noticed this a while ago but it seemed to go away for me. It might be related to the intensity of the song - rapid notes might accumulate a deejay and then a quiet gap lets it catch up.

I'll look into it again the next time I have it all hooked up.

The only think I can think it might be just now it's that beat saber is sending haptic events with a duration of X, and sending them more frequently than 1/X, and I'm queuing them rather than dropping the over lap
________________________________
From: WattleFoxxo ***@***.***>
Sent: Wednesday, December 21, 2022 1:11:19 AM
To: mm0zct/Oculus_Touch_Steam_Link ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mm0zct/Oculus_Touch_Steam_Link] Haptics are delayed in Beatsaber (Issue #10)


In the menu it's responsive but once the level starts the haptics get more and more delayed.

Specs:
HMD: HP Reverb G2.
OS: Windows 11 Pro 64 bit.
CPU: Ryzen 7 7700X.
RAM: 32 GB DDR5
GPU: AMD RX 6800XT

**Comment by WattleFoxxo** [comment]
I've also noticed the same thing in vrchat when hovering over lots of objects.

**Comment by WattleFoxxo** [comment]
A temp fix I found was trying it with every usb port and finding one that worked.

**Comment by WattleFoxxo** [comment]
This seems to be a oculus and usb issue.
