### ISSUE TITLE
Launching the game on the wrong HMD

### ISSUE THREAD

**Issue by Cotizin** [mm0zct/Oculus_Touch_Steam_Link#19]
Hi. I've been trying to use rift CV1 controllers to replace the broken wands from my HTC vive headset. SteamVR detects the controllers just fine and i've even calibrated them to the correct place, but everytime i try to launch a game, that's not VRchat, the game launches on the oculus rift instead of the HTC vive.
Also, the option to "render in headset" in the "ovr_Test" launcher is disable and i don't even seem to be capable of enableing it.
What am i missing?

**Comment by mm0zct** [comment]
Hi Cotizin,

Do you have steam vr set as you open xr runtime? Sometimes oculus likes to re-register itself as the openxr runtime handler. If this is not the problem, then the issue is with the game detecting available runtimes and auto selecting oculus api, many games have a launch argument to force it to oculus or steam vr.

With regards to the render in headset, it's mostly deprecated but you can enable it in the config file that is generated by ovr test before you start ovr test again, or launch it from a bat file with the right arguments. You shouldn't really need to do this though, I would stick to not rendering the black screen to the headset. Odtkra will lower the render resolution to just a few pixels anyway.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Cotizin ***@***.***>
Sent: Sunday, September 10, 2023 1:19:01 AM
To: mm0zct/Oculus_Touch_Steam_Link ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mm0zct/Oculus_Touch_Steam_Link] Launching the game on the wrong HMD (Issue #19)


Hi. I've been trying to use rift CV1 controllers to replace the broken wands from my HTC vive headset. SteamVR detects the controllers just fine and i've even calibrated them to the correct place, but everytime i try to launch a game, that's not VRchat, the game launches on the oculus rift instead of the HTC vive.
Also, the option to "render in headset" in the "ovr_Test" launcher is disable and i don't even seem to be capable of enableing it.
What am i missing?

**Comment by Cotizin** [comment]
> 

Nice, it seems the launch argument worked. SteamVR was already my runtime option for open xr, this time i setted my OVR Advanced Settings to force games to steamVR and that kinda worked.
I tested on 2 games that were giving me trouble: Rise of the Tomb Raider and Zero Caliber. As result ZC finally booted through my HTC vive! But ROTTR simply crashes instantly and doesn't show anything on screen.

It would be nice if you happen to know why that is happening, but otherwise i'm just really glad you could help me with my problem so quicly! That's probably gonna get me through most of SteamVR games with no problem.
Thx a lot.
