### ISSUE TITLE
Is it possible to get the OculusTouchLink to be compatible with the Valve Index or other headsets?

### ISSUE THREAD

**Issue by CrispyDude1** [mm0zct/Oculus_Touch_Steam_Link#21]
I was wondering if it was possible for the **OculusTouchLink\ovr_test** functions to work with the Valve Index headset or other headsets. 

Like for the **ovr_test** I was thinking maybe it could be possible to get those features to work on the Valve Index headset so you can use some of those settings such as: 

**"Prediction latency (ms)"**
**"Haptic Scale Factor"** 
**"Haptic Minimum Value"** 
**"World Position Offset X Y Z"** 

without the need of having an Oculus headset product. 

So basically, a version that works with the Valve Index headset or other headsets. And the features on the **"OVR_test"** could work on the Valve Index HMD headset so then that way you can use the settings for it without getting errors saying that it can't work.

I'm not sure how hard it is to set up, but it will be pretty awesome if it could work, so then that way for people who don't have an Oculus headset, and they use other headsets such as **Valve Index,** **HTC Vive,** etc, 

they can instead just use the version that was made for other headsets and use some of the features in it without the need of using the Oculus headset to use the features.

**Comment by mm0zct** [comment]
I'm afraid everything in this tool is related to translating the oculus api into steam vr, there is no mechanism in the program to hook into existing steam vr devices and manipulate their behaviour. Everything I provide to tweak is just to try and let the user adjust for things that might feel off because I haven't integrated perfectly into the steam vr api. Native devices should already be giving you the developer's intended user experience.
